server:
  port: 8080
  jwt_secret: "medtrust_secure_jwt_secret_key_2026"
  jwt_expire_hours: 24

database:
  dsn: "root:123456@tcp(127.0.0.1:3306)/medtrust?charset=utf8mb4&parseTime=True&loc=Local"

ipfs:
  api_url: "http://127.0.0.1:5001"
  storage_dir: "./data/ipfs_storage"

blockchain:
  channel_id: "medicalchannel"
  chaincode_id: "medicalcontract"
  ledger_dir: "./data/fabric_ledger"
  fabric:
    enabled: false
    peer_endpoint: "127.0.0.1:7051"
    gateway_peer: "peer0.orga.medical.com"
    msp_id: "OrgAMSP"
    tls_cert_path: "./fabric_crypto/tls/ca.crt"
    cert_path: "./fabric_crypto/users/User1@orga.medical.com/msp/signcerts/cert.pem"
    key_path: "./fabric_crypto/users/User1@orga.medical.com/msp/keystore"

risk:
  low_threshold: 30
  high_threshold: 60
